Fix updateStrategy in YAML
Fix updateStrategy in YAML. It is a map on Kube 1.21.

I was getting this message:
```
error: error validating "02.yaml": error validating data: ValidationError(StatefulSet.spec.updateStrategy): invalid type for io.k8s.api.apps.v1.StatefulSetUpdateStrategy: got "string", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false
```